/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Temp;

/**
 *
 * @author mingming
 */
public class CreateAccount extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel1.setText("Campus card number:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(39, 18, 138, 16);

        jTextField1.setText("            ");
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 28));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(183, 12, 62, 28);

        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(114, 52, 63, 16);

        jTextField2.setText("            ");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(183, 46, 62, 28);

        jLabel3.setText("Confirm Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(59, 86, 118, 16);

        jTextField3.setText("            ");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(183, 80, 62, 28);

        jLabel4.setText("Deposite amount:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(65, 120, 112, 16);

        jTextField4.setText("            ");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(183, 114, 62, 28);

        jLabel5.setText("Daily Calorie Limit:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(57, 154, 120, 16);

        jTextField5.setText("            ");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(183, 148, 62, 28);

        jButton1.setText("Submit");
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 194, 88, 29);

        jButton2.setText("Clear");
        jPanel1.add(jButton2);
        jButton2.setBounds(168, 194, 76, 29);

        jButton3.setText("Back");
        jPanel1.add(jButton3);
        jButton3.setBounds(87, 194, 75, 29);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CampusSmartCafe/view/login.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 400, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
