/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Temp;

/**
 *
 * @author mingming
 */
public class Map extends javax.swing.JPanel {

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cafe1 = new javax.swing.JButton();
        Cafe2 = new javax.swing.JButton();
        Cafe3 = new javax.swing.JButton();
        Cafe4 = new javax.swing.JButton();
        Cafe5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        Cafe1.setText("Cafe1");
        Cafe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cafe1ActionPerformed(evt);
            }
        });
        add(Cafe1);
        Cafe1.setBounds(90, 120, 80, 29);

        Cafe2.setText("Cafe2");
        add(Cafe2);
        Cafe2.setBounds(350, 60, 80, 29);

        Cafe3.setText("Cafe3");
        Cafe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cafe3ActionPerformed(evt);
            }
        });
        add(Cafe3);
        Cafe3.setBounds(350, 180, 80, 29);

        Cafe4.setText("Cafe4");
        Cafe4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cafe4ActionPerformed(evt);
            }
        });
        add(Cafe4);
        Cafe4.setBounds(60, 290, 97, 29);

        Cafe5.setText("Cafe5");
        Cafe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cafe5ActionPerformed(evt);
            }
        });
        add(Cafe5);
        Cafe5.setBounds(170, 350, 97, 29);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CampusSmartCafe/view/campusmap2.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        add(jLabel2);
        jLabel2.setBounds(-200, -200, 930, 798);
    }// </editor-fold>//GEN-END:initComponents

    private void Cafe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cafe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cafe1ActionPerformed

    private void Cafe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cafe3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cafe3ActionPerformed

    private void Cafe4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cafe4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cafe4ActionPerformed

    private void Cafe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cafe5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cafe5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cafe1;
    private javax.swing.JButton Cafe2;
    private javax.swing.JButton Cafe3;
    private javax.swing.JButton Cafe4;
    private javax.swing.JButton Cafe5;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
